<?php

namespace MissionBundle\Repository;

/**
 * MissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionRepository extends \Doctrine\ORM\EntityRepository
{
    public function listAllMission($userId){
        $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM MissionBundle:Mission m
                JOIN m.client u
                WHERE m.client = 2
                '
            )
//            ->setParameter('userId', $userId)
            ->getResult();
    }
}
