services:
#    mission.example:
#        class: MissionBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    mission.mission_management:
        class: MissionBundle\Service\MissionManagement
        argument:
          - '@service_container'
          - '@doctrine.orm.entity_manager'